language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '12'
  - '11'
  - '10'

before_success:
  - npm run build

script:
  - npm test

after_success:
  - npm run typedoc
  - npm run coverage

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: '$GH_TOKEN'
    on:
      tags: true
